require("telescope").load_extension("noice")

local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>fp', builtin.git_files, { desc = "Find Git Files" })
vim.keymap.set('n', '<leader>fg', function()
    builtin.grep_string({ search = vim.fn.input("Grep > ") })
end, { desc = "Grep String" })
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = "Find Files" })
vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = "Find Buffers" })
vim.keymap.set('n', '<leader>fh', builtin.help_tags, { desc = "Find Help" })
vim.keymap.set('n', '<leader>flr', builtin.lsp_references, { desc = "Find References" })
